<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PackageIcon>app-icon-white-128.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Images\app-icon-white-258.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MVVM\Model\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Images\app-icon-white-128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
